# Generated by Django 6.0.3 on 2026-03-18 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Danh mục', 'verbose_name_plural': 'Các danh mục'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Sản phẩm', 'verbose_name_plural': 'Các sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='stockhistory',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Lịch sử kho', 'verbose_name_plural': 'Lịch sử nhập xuất'},
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='Mô tả danh mục'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=0, verbose_name='Số lượng tồn kho hiện tại'),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='quantity',
            field=models.IntegerField(verbose_name='Số lượng thay đổi'),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian thực hiện'),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='type',
            field=models.CharField(choices=[('IN', 'Nhập kho (Nhập thêm hàng)'), ('OUT', 'Xuất kho (Bán hàng/Hỏng)')], max_length=10, verbose_name='Loại giao dịch'),
        ),
    ]
