# Generated by Django 6.0.3 on 2026-03-23 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_orderitem_options_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên cửa hàng')),
                ('address', models.CharField(max_length=500, verbose_name='Địa chỉ')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stores/', verbose_name='Ảnh cửa hàng')),
            ],
            options={
                'verbose_name': 'Cửa hàng',
                'verbose_name_plural': 'Danh sách Cửa hàng',
            },
        ),
    ]
