# Generated by Django 6.0.2 on 2026-04-13 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_category_options_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Tiêu đề chính')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Tiêu đề phụ')),
                ('image', models.ImageField(upload_to='banners/')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='Đường dẫn nút')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự')),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
    ]
